### ISSUE TITLE
bakclog

### ISSUE THREAD

**Issue by husseinbouik** [labs-web/lab-scrum#4]
# Backlog 

## Travail à faire

- Création de la liste des tâches
- Validation avec le formateur
- Création des issues
- Changement les noms des fichier dans le dossier backlog :
    - Ordre.Titre_issue.Numero_issue.md
- Les issues sont enregistrer dans des sous-dossiers qui représente des labels des issues

## Livrable
- backlog/*

**Comment by essarraj-fouad** [comment]
Il existe des conflits
